### ISSUE TITLE
i am an idiot

### ISSUE THREAD

**Issue by savimportweb** [ejmg/an-idiots-guide-to-installing-arch-on-a-lenovo-carbon-x1-gen-6#6]
Hello, thanks for the guide,

however we all don't have that much money for such a good computer. some of us are still in the core duo era and are fine with it (sometimes...)

so i tried installing arch using your guide. it didnt work.

i repeat i am an idiot.

i will try to fix this issue by buying a better laptop soon. thanks for pointing out this one.

**Comment by ejmg** [comment]
Friend,,,,,, while we are all idiots, you are definitely not an idiot for having a cheaper laptop.

I have an internship right now which helped a lot, but I am definitely...... hurting a little bit from buying the laptop 😑. It's also why I made this: since I didn't mess up my expensive laptop, I would like to also help others not ruin theirs either, haha.

I highly recommend any of the lenovos, and, if you get a more up to date one (particularly with a new cpu), you could definitely use this guide still. Thanks for reading!
